[toolchain]
anchor_version = "0.29.0"
solana_version = "1.18.20"

[features]
#resolution = true
skip-lint = false

[programs.localnet]
blockmesh-program = "FRkQxATWhWqkj3SPZmbBCtkVM4fChd6VYLbEGhgCuHHJ"
merkle-distributor = "AZMc26abaSP7si1wtLaV5yPxTxpWd895M8YpJFFdQ8Qw"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[workspace]
members = ["programs/blockmesh-program", "programs/merkle-distributor"]

[scripts]
#test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/merkle-distributor-test.ts"
