[toolchain]
anchor_version = "0.29.0"
solana_version = "1.18.20"

[features]
#resolution = true
skip-lint = false

# solana program extend AZMc26abaSP7si1wtLaV5yPxTxpWd895M8YpJFFdQ8Qw 100000


# solana program show --buffers
# solana program close --buffer
# anchor deploy --program-name "merkle-distributor"  --provider.cluster "https://mainnet.helius-rpc.com/?api-key=0b25ef9e-0fd3-4fb5-a5fb-deec31b9017b" -- -- --with-compute-unit-price 50000
# solana program deploy --use-rpc \
# --max-sign-attempts 60 --with-compute-unit-price 60000 \
# --program-id AZMc26abaSP7si1wtLaV5yPxTxpWd895M8YpJFFdQ8Qw  --use-quic --allow-excessive-deploy-account-balance \
# --url "" \
# target/deploy/merkle_distributor.so

# anchor idl upgrade --filepath target/idl/merkle_distributor.json AZMc26abaSP7si1wtLaV5yPxTxpWd895M8YpJFFdQ8Qw  --provider.cluster "https://mainnet.helius-rpc.com/?api-key=0b25ef9e-0fd3-4fb5-a5fb-deec31b9017b"


[programs.localnet]
blockmesh-program = "FRkQxATWhWqkj3SPZmbBCtkVM4fChd6VYLbEGhgCuHHJ"
merkle-distributor = "AZMc26abaSP7si1wtLaV5yPxTxpWd895M8YpJFFdQ8Qw"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[workspace]
members = ["programs/blockmesh-program", "programs/merkle-distributor"]

[scripts]
#test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/merkle-distributor-test.ts"
